language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
